# -*- coding: utf-8 -*-

from odoo import models, fields, api


class sumex_apps_sage_inherits_sage_partner_inherit(models.Model):

	_inherit = 'res.partner'

	_created_from_sumex_apps_imports_csv_of_sage = fields.Boolean("From import CSV of Sage", required = False)

	_sage_field_codigoempresa = fields.Char(required = False, string = '_sage_field_codigoempresa')
	_sage_field_iddelegacion = fields.Char(required = False, string = '_sage_field_iddelegacion')
	_sage_field_codigocliente = fields.Char(required = False, string = '_sage_field_codigocliente')
	_sage_field_siglanacion = fields.Char(required = False, string = '_sage_field_siglanacion')
	_sage_field_cifdni = fields.Char(required = False, string = '_sage_field_cifdni')
	_sage_field_cifeuropeo = fields.Char(required = False, string = '_sage_field_cifeuropeo')
	_sage_field_fechaalta = fields.Char(required = False, string = '_sage_field_fechaalta')
	_sage_field_codigoproveedor = fields.Char(required = False, string = '_sage_field_codigoproveedor')
	_sage_field_codigocontable = fields.Char(required = False, string = '_sage_field_codigocontable')
	_sage_field_codigocadena = fields.Char(required = False, string = '_sage_field_codigocadena')
	_sage_field_codigocategoriacliente = fields.Char(required = False, string = '_sage_field_codigocategoriacliente')
	_sage_field_codigodefinicion = fields.Char(required = False, string = '_sage_field_codigodefinicion')
	_sage_field_referenciaedi = fields.Char(required = False, string = '_sage_field_referenciaedi')
	_sage_field_activarlogicnet = fields.Char(required = False, string = '_sage_field_activarlogicnet')
	_sage_field_usuariologicnet = fields.Char(required = False, string = '_sage_field_usuariologicnet')
	_sage_field_contraseñalogicnet = fields.Char(required = False, string = '_sage_field_contraseñalogicnet')
	_sage_field_codigoexportacion = fields.Char(required = False, string = '_sage_field_codigoexportacion')
	_sage_field_condicionexportacion = fields.Char(required = False, string = '_sage_field_condicionexportacion')
	_sage_field_codigodivisa = fields.Char(required = False, string = '_sage_field_codigodivisa')
	_sage_field_codigocondiciones = fields.Char(required = False, string = '_sage_field_codigocondiciones')
	_sage_field_codigoidioma = fields.Char(required = False, string = '_sage_field_codigoidioma')
	_sage_field_razonsocial = fields.Char(required = False, string = '_sage_field_razonsocial')
	_sage_field_razonsocial2 = fields.Char(required = False, string = '_sage_field_razonsocial2')
	_sage_field_nombre = fields.Char(required = False, string = '_sage_field_nombre')
	_sage_field_domicilio = fields.Char(required = False, string = '_sage_field_domicilio')
	_sage_field_domicilio2 = fields.Char(required = False, string = '_sage_field_domicilio2')
	_sage_field_actividad = fields.Char(required = False, string = '_sage_field_actividad')
	_sage_field_tipocliente = fields.Char(required = False, string = '_sage_field_tipocliente')
	_sage_field_codigosector = fields.Char(required = False, string = '_sage_field_codigosector')
	_sage_field_marca = fields.Char(required = False, string = '_sage_field_marca')
	_sage_field_cargo1 = fields.Char(required = False, string = '_sage_field_cargo1')
	_sage_field_nombre1 = fields.Char(required = False, string = '_sage_field_nombre1')
	_sage_field_cargo2 = fields.Char(required = False, string = '_sage_field_cargo2')
	_sage_field_nombre2 = fields.Char(required = False, string = '_sage_field_nombre2')
	_sage_field_cargo3 = fields.Char(required = False, string = '_sage_field_cargo3')
	_sage_field_nombre3 = fields.Char(required = False, string = '_sage_field_nombre3')
	_sage_field_formadepago = fields.Char(required = False, string = '_sage_field_formadepago')
	_sage_field_domicilioenvio = fields.Char(required = False, string = '_sage_field_domicilioenvio')
	_sage_field_domiciliofactura = fields.Char(required = False, string = '_sage_field_domiciliofactura')
	_sage_field_domiciliorecibo = fields.Char(required = False, string = '_sage_field_domiciliorecibo')
	_sage_field_codigobanco = fields.Char(required = False, string = '_sage_field_codigobanco')
	_sage_field_codigoagencia = fields.Char(required = False, string = '_sage_field_codigoagencia')
	_sage_field_dc = fields.Char(required = False, string = '_sage_field_dc')
	_sage_field_ccc = fields.Char(required = False, string = '_sage_field_ccc')
	_sage_field_iban = fields.Char(required = False, string = '_sage_field_iban')
	_sage_field_bloqueopedido = fields.Char(required = False, string = '_sage_field_bloqueopedido')
	_sage_field_bloqueoalbaran = fields.Char(required = False, string = '_sage_field_bloqueoalbaran')
	_sage_field_codigocanal = fields.Char(required = False, string = '_sage_field_codigocanal')
	_sage_field_codigoproyecto = fields.Char(required = False, string = '_sage_field_codigoproyecto')
	_sage_field_codigoseccion = fields.Char(required = False, string = '_sage_field_codigoseccion')
	_sage_field_codigodepartamento = fields.Char(required = False, string = '_sage_field_codigodepartamento')
	_sage_field_tarifaprecio = fields.Char(required = False, string = '_sage_field_tarifaprecio')
	_sage_field_tarifadescuento = fields.Char(required = False, string = '_sage_field_tarifadescuento')
	_sage_field_mantenercambio = fields.Char(required = False, string = '_sage_field_mantenercambio')
	_sage_field_indicadoriva = fields.Char(required = False, string = '_sage_field_indicadoriva')
	_sage_field_grupoiva = fields.Char(required = False, string = '_sage_field_grupoiva')
	_sage_field_percent_descuento = fields.Char(required = False, string = '_sage_field_percent_descuento')
	_sage_field_percent_prontopago = fields.Char(required = False, string = '_sage_field_percent_prontopago')
	_sage_field_percent_retencion = fields.Char(required = False, string = '_sage_field_percent_retencion')
	_sage_field_percent_financiacion = fields.Char(required = False, string = '_sage_field_percent_financiacion')
	_sage_field_percent_rappel = fields.Char(required = False, string = '_sage_field_percent_rappel')
	_sage_field_codigocomisionista = fields.Char(required = False, string = '_sage_field_codigocomisionista')
	_sage_field_codigocomisionista2 = fields.Char(required = False, string = '_sage_field_codigocomisionista2')
	_sage_field_codigocomisionista3 = fields.Char(required = False, string = '_sage_field_codigocomisionista3')
	_sage_field_codigocomisionista4 = fields.Char(required = False, string = '_sage_field_codigocomisionista4')
	_sage_field_codigojefezona = fields.Char(required = False, string = '_sage_field_codigojefezona')
	_sage_field_percent_comision = fields.Char(required = False, string = '_sage_field_percent_comision')
	_sage_field_percent_comision2 = fields.Char(required = False, string = '_sage_field_percent_comision2')
	_sage_field_percent_comision3 = fields.Char(required = False, string = '_sage_field_percent_comision3')
	_sage_field_percent_comision4 = fields.Char(required = False, string = '_sage_field_percent_comision4')
	_sage_field_comisionsobrezona_percent = fields.Char(required = False, string = '_sage_field_comisionsobrezona_percent')
	_sage_field_codigozona = fields.Char(required = False, string = '_sage_field_codigozona')
	_sage_field_codigoruta = fields.Char(required = False, string = '_sage_field_codigoruta')
	_sage_field_codigotransportista = fields.Char(required = False, string = '_sage_field_codigotransportista')
	_sage_field_tipoportes = fields.Char(required = False, string = '_sage_field_tipoportes')
	_sage_field_observacionescliente = fields.Char(required = False, string = '_sage_field_observacionescliente')
	_sage_field_comentarios = fields.Char(required = False, string = '_sage_field_comentarios')
	_sage_field_periodicidadfacturas = fields.Char(required = False, string = '_sage_field_periodicidadfacturas')
	_sage_field_agruparalbaranes = fields.Char(required = False, string = '_sage_field_agruparalbaranes')
	_sage_field_agruparabonos = fields.Char(required = False, string = '_sage_field_agruparabonos')
	_sage_field_albaranvalorado = fields.Char(required = False, string = '_sage_field_albaranvalorado')
	_sage_field_servircompleto = fields.Char(required = False, string = '_sage_field_servircompleto')
	_sage_field_mascaraoferta = fields.Char(required = False, string = '_sage_field_mascaraoferta')
	_sage_field_mascarapedido = fields.Char(required = False, string = '_sage_field_mascarapedido')
	_sage_field_mascaraalbaran = fields.Char(required = False, string = '_sage_field_mascaraalbaran')
	_sage_field_mascarafactura = fields.Char(required = False, string = '_sage_field_mascarafactura')
	_sage_field_mascararecibo = fields.Char(required = False, string = '_sage_field_mascararecibo')
	_sage_field_serieoferta = fields.Char(required = False, string = '_sage_field_serieoferta')
	_sage_field_seriepedido = fields.Char(required = False, string = '_sage_field_seriepedido')
	_sage_field_seriealbaran = fields.Char(required = False, string = '_sage_field_seriealbaran')
	_sage_field_copiasalbaran = fields.Char(required = False, string = '_sage_field_copiasalbaran')
	_sage_field_copiasfactura = fields.Char(required = False, string = '_sage_field_copiasfactura')
	_sage_field_copiasoferta = fields.Char(required = False, string = '_sage_field_copiasoferta')
	_sage_field_copiaspedido = fields.Char(required = False, string = '_sage_field_copiaspedido')
	_sage_field_codigosigla = fields.Char(required = False, string = '_sage_field_codigosigla')
	_sage_field_viapublica = fields.Char(required = False, string = '_sage_field_viapublica')
	_sage_field_numero1 = fields.Char(required = False, string = '_sage_field_numero1')
	_sage_field_numero2 = fields.Char(required = False, string = '_sage_field_numero2')
	_sage_field_escalera = fields.Char(required = False, string = '_sage_field_escalera')
	_sage_field_piso = fields.Char(required = False, string = '_sage_field_piso')
	_sage_field_puerta = fields.Char(required = False, string = '_sage_field_puerta')
	_sage_field_letra = fields.Char(required = False, string = '_sage_field_letra')
	_sage_field_codigopostal = fields.Char(required = False, string = '_sage_field_codigopostal')
	_sage_field_codigomunicipio = fields.Char(required = False, string = '_sage_field_codigomunicipio')
	_sage_field_municipio = fields.Char(required = False, string = '_sage_field_municipio')
	_sage_field_colamunicipio = fields.Char(required = False, string = '_sage_field_colamunicipio')
	_sage_field_codigoprovincia = fields.Char(required = False, string = '_sage_field_codigoprovincia')
	_sage_field_provincia = fields.Char(required = False, string = '_sage_field_provincia')
	_sage_field_codigonacion = fields.Char(required = False, string = '_sage_field_codigonacion')
	_sage_field_nacion = fields.Char(required = False, string = '_sage_field_nacion')
	_sage_field_telefono = fields.Char(required = False, string = '_sage_field_telefono')
	_sage_field_telefono2 = fields.Char(required = False, string = '_sage_field_telefono2')
	_sage_field_telefono3 = fields.Char(required = False, string = '_sage_field_telefono3')
	_sage_field_fax = fields.Char(required = False, string = '_sage_field_fax')
	_sage_field_email1 = fields.Char(required = False, string = '_sage_field_email1')
	_sage_field_email2 = fields.Char(required = False, string = '_sage_field_email2')
	_sage_field_bajaempresalc = fields.Char(required = False, string = '_sage_field_bajaempresalc')
	_sage_field_fechabajalc = fields.Char(required = False, string = '_sage_field_fechabajalc')
	_sage_field_codigomotivobajaclientelc = fields.Char(required = False, string = '_sage_field_codigomotivobajaclientelc')
	_sage_field_comercialasignadolc = fields.Char(required = False, string = '_sage_field_comercialasignadolc')
	_sage_field_codigotipoclientelc = fields.Char(required = False, string = '_sage_field_codigotipoclientelc')
	_sage_field_fechaultimaaccionlc = fields.Char(required = False, string = '_sage_field_fechaultimaaccionlc')
	_sage_field_personaclientelc = fields.Char(required = False, string = '_sage_field_personaclientelc')
	_sage_field_codigoactividadlc = fields.Char(required = False, string = '_sage_field_codigoactividadlc')
	_sage_field_codigosubactividadlc = fields.Char(required = False, string = '_sage_field_codigosubactividadlc')
	_sage_field_codigocargo1 = fields.Char(required = False, string = '_sage_field_codigocargo1')
	_sage_field_codigocargo2 = fields.Char(required = False, string = '_sage_field_codigocargo2')
	_sage_field_codigocargo3 = fields.Char(required = False, string = '_sage_field_codigocargo3')
	_sage_field_codigodivisionlc = fields.Char(required = False, string = '_sage_field_codigodivisionlc')
	_sage_field_codigoambitoclientelc = fields.Char(required = False, string = '_sage_field_codigoambitoclientelc')
	_sage_field_codigoclaseclientelc = fields.Char(required = False, string = '_sage_field_codigoclaseclientelc')
	_sage_field_codigogrupoclientelc = fields.Char(required = False, string = '_sage_field_codigogrupoclientelc')
	_sage_field_iddelegacioncentrallc = fields.Char(required = False, string = '_sage_field_iddelegacioncentrallc')
	_sage_field_horariodomiciliolc = fields.Char(required = False, string = '_sage_field_horariodomiciliolc')
	_sage_field_codigocolectivoclientelc = fields.Char(required = False, string = '_sage_field_codigocolectivoclientelc')
	_sage_field_codigotipoprimercontactolc = fields.Char(required = False, string = '_sage_field_codigotipoprimercontactolc')
	_sage_field_fechaproximaaccionlc = fields.Char(required = False, string = '_sage_field_fechaproximaaccionlc')
	_sage_field_autorizacionlopdlc = fields.Char(required = False, string = '_sage_field_autorizacionlopdlc')
	_sage_field_fechaautorizacionlopdlc = fields.Char(required = False, string = '_sage_field_fechaautorizacionlopdlc')
	_sage_field_excluirporlopdlc = fields.Char(required = False, string = '_sage_field_excluirporlopdlc')
	_sage_field_fechaexcluirporlopdlc = fields.Char(required = False, string = '_sage_field_fechaexcluirporlopdlc')
	_sage_field_riesgomaximo = fields.Char(required = False, string = '_sage_field_riesgomaximo')
	_sage_field_referenciadelproveedor = fields.Char(required = False, string = '_sage_field_referenciadelproveedor')
	_sage_field_destinoedi = fields.Char(required = False, string = '_sage_field_destinoedi')
	_sage_field_codigonaturaleza = fields.Char(required = False, string = '_sage_field_codigonaturaleza')
	_sage_field_codigotransporte = fields.Char(required = False, string = '_sage_field_codigotransporte')
	_sage_field_codigopuerto = fields.Char(required = False, string = '_sage_field_codigopuerto')
	_sage_field_codigoregimenestadistico = fields.Char(required = False, string = '_sage_field_codigoregimenestadistico')
	_sage_field_envioefactura = fields.Char(required = False, string = '_sage_field_envioefactura')
	_sage_field_emailenvioefactura = fields.Char(required = False, string = '_sage_field_emailenvioefactura')
	_sage_field_guiaxmlefactura = fields.Char(required = False, string = '_sage_field_guiaxmlefactura')
	_sage_field_departamentoedi = fields.Char(required = False, string = '_sage_field_departamentoedi')
	_sage_field_sabadosfestivos = fields.Char(required = False, string = '_sage_field_sabadosfestivos')
	_sage_field_domingosfestivos = fields.Char(required = False, string = '_sage_field_domingosfestivos')
	_sage_field_formatoefactura = fields.Char(required = False, string = '_sage_field_formatoefactura')
	_sage_field_notraspasarsfa = fields.Char(required = False, string = '_sage_field_notraspasarsfa')
	_sage_field_cuentaprovision = fields.Char(required = False, string = '_sage_field_cuentaprovision')
	_sage_field_liquidacionendespacho = fields.Char(required = False, string = '_sage_field_liquidacionendespacho')
	_sage_field_codigocontableant = fields.Char(required = False, string = '_sage_field_codigocontableant')
	_sage_field_cuentaprovisionant = fields.Char(required = False, string = '_sage_field_cuentaprovisionant')
	_sage_field_formatoenvio = fields.Char(required = False, string = '_sage_field_formatoenvio')
	_sage_field_puntossr = fields.Char(required = False, string = '_sage_field_puntossr')
	_sage_field_tarjetasr = fields.Char(required = False, string = '_sage_field_tarjetasr')
	_sage_field_fechanacimiento = fields.Char(required = False, string = '_sage_field_fechanacimiento')
	_sage_field_personaasignada = fields.Char(required = False, string = '_sage_field_personaasignada')
	_sage_field_asesornominalw = fields.Char(required = False, string = '_sage_field_asesornominalw')
	_sage_field_empresanominalwin = fields.Char(required = False, string = '_sage_field_empresanominalwin')
	_sage_field_codigoempleado = fields.Char(required = False, string = '_sage_field_codigoempleado')
	_sage_field_idcliente = fields.Char(required = False, string = '_sage_field_idcliente')
	_sage_field_publicargcrm = fields.Char(required = False, string = '_sage_field_publicargcrm')
	_sage_field_referenciamandato = fields.Char(required = False, string = '_sage_field_referenciamandato')
	_sage_field_fechamodificacion = fields.Char(required = False, string = '_sage_field_fechamodificacion')
	_sage_field_sumex_referenciaedipagador = fields.Char(required = False, string = '_sage_field_sumex_referenciaedipagador')
	_sage_field_sumex_clienteriesgo = fields.Char(required = False, string = '_sage_field_sumex_clienteriesgo')
	_sage_field_sumex_fechaaltariesgo = fields.Char(required = False, string = '_sage_field_sumex_fechaaltariesgo')
	_sage_field_sumex_riesgofechah1 = fields.Char(required = False, string = '_sage_field_sumex_riesgofechah1')
	_sage_field_sumex_riesgofechah2 = fields.Char(required = False, string = '_sage_field_sumex_riesgofechah2')
	_sage_field_sumex_riesgofechah3 = fields.Char(required = False, string = '_sage_field_sumex_riesgofechah3')
	_sage_field_sumex_riesgofechah4 = fields.Char(required = False, string = '_sage_field_sumex_riesgofechah4')
	_sage_field_sumex_riesgoh1 = fields.Char(required = False, string = '_sage_field_sumex_riesgoh1')
	_sage_field_sumex_riesgoh2 = fields.Char(required = False, string = '_sage_field_sumex_riesgoh2')
	_sage_field_sumex_riesgoh3 = fields.Char(required = False, string = '_sage_field_sumex_riesgoh3')
	_sage_field_sumex_riesgoh4 = fields.Char(required = False, string = '_sage_field_sumex_riesgoh4')
	_sage_field_sumex_observacionesriesgo = fields.Char(required = False, string = '_sage_field_sumex_observacionesriesgo')
	_sage_field_s_aplicarbaremost = fields.Char(required = False, string = '_sage_field_s_aplicarbaremost')
	_sage_field_social1 = fields.Char(required = False, string = '_sage_field_social1')
	_sage_field_social2 = fields.Char(required = False, string = '_sage_field_social2')
	_sage_field_social3 = fields.Char(required = False, string = '_sage_field_social3')
	_sage_field_social4 = fields.Char(required = False, string = '_sage_field_social4')
	_sage_field_telefonoaccion = fields.Char(required = False, string = '_sage_field_telefonoaccion')
	_sage_field_telefono2accion = fields.Char(required = False, string = '_sage_field_telefono2accion')
	_sage_field_telefono3accion = fields.Char(required = False, string = '_sage_field_telefono3accion')
	_sage_field_social1accion = fields.Char(required = False, string = '_sage_field_social1accion')
	_sage_field_social2accion = fields.Char(required = False, string = '_sage_field_social2accion')
	_sage_field_social3accion = fields.Char(required = False, string = '_sage_field_social3accion')
	_sage_field_social4accion = fields.Char(required = False, string = '_sage_field_social4accion')
	_sage_field_sumex_codigorecargo = fields.Char(required = False, string = '_sage_field_sumex_codigorecargo')
	_sage_field_sumex_importerecargo = fields.Char(required = False, string = '_sage_field_sumex_importerecargo')
	_sage_field_sumex_porrecargo = fields.Char(required = False, string = '_sage_field_sumex_porrecargo')
	_sage_field_cuentagasto = fields.Char(required = False, string = '_sage_field_cuentagasto')
	_sage_field_comentarioasiento = fields.Char(required = False, string = '_sage_field_comentarioasiento')
	_sage_field_dire = fields.Char(required = False, string = '_sage_field_dire')
	_sage_field_idclientepago = fields.Char(required = False, string = '_sage_field_idclientepago')
	_sage_field_statuswf = fields.Char(required = False, string = '_sage_field_statuswf')

	@api.model
	def create(self, vals_list):

		if 'from_import_csv' not in self._context:
			return super(sumex_apps_sage_inherits_sage_partner_inherit, self).create(vals_list)
		vals_list['_created_from_sumex_apps_imports_csv_of_sage'] = True
		rows = super(sumex_apps_sage_inherits_sage_partner_inherit, self).create(vals_list)
		return rows

	def write(self, vals_list):

		if 'from_import_csv' not in self._context:
			return super(sumex_apps_sage_inherits_sage_partner_inherit, self).write(vals_list)
		vals_list['_created_from_sumex_apps_imports_csv_of_sage'] = True
		rows = super(sumex_apps_sage_inherits_sage_partner_inherit, self).write(vals_list)
		return rows
