# -*- coding: utf-8 -*-

from odoo import models, fields, api


class sumex_apps_sage_inherits_sage_sale_order_inherit(models.Model):

	_inherit = 'sale.order'

	_created_from_sumex_apps_imports_csv_of_sage_ventas = fields.Boolean("From import CSV of Sage Ventas", required = False)

	_sage_field_nacion = fields.Char(required = False, string = '_sage_field_nacion')
	_sage_field_razonsocial = fields.Char(required = False, string = '_sage_field_razonsocial')
	_sage_field_cifeuropeo = fields.Char(required = False, string = '_sage_field_cifeuropeo')
	_sage_field_nombre = fields.Char(required = False, string = '_sage_field_nombre')
	_sage_field_numerolineas = fields.Char(required = False, string = '_sage_field_numerolineas')
	_sage_field_domicilio = fields.Char(required = False, string = '_sage_field_domicilio')
	_sage_field_codigopostal = fields.Char(required = False, string = '_sage_field_codigopostal')
	_sage_field_municipio = fields.Char(required = False, string = '_sage_field_municipio')
	_sage_field_colamunicipio = fields.Char(required = False, string = '_sage_field_colamunicipio')
	_sage_field_seriepedido = fields.Char(required = False, string = '_sage_field_seriepedido')
	_sage_field_numeropedido = fields.Char(required = False, string = '_sage_field_numeropedido')
	_sage_field_ejerciciopedido = fields.Char(required = False, string = '_sage_field_ejerciciopedido')
	_sage_field_codigocliente = fields.Char(required = False, string = '_sage_field_codigocliente')
	_sage_field_codigocadena = fields.Char(required = False, string = '_sage_field_codigocadena')
	_sage_field_siglanacion = fields.Char(required = False, string = '_sage_field_siglanacion')
	_sage_field_fechapedido = fields.Char(required = False, string = '_sage_field_fechapedido')
	_sage_field_formadepago = fields.Char(required = False, string = '_sage_field_formadepago')
	_sage_field_numeroplazos = fields.Char(required = False, string = '_sage_field_numeroplazos')
	_sage_field_diasprimerplazo = fields.Char(required = False, string = '_sage_field_diasprimerplazo')
	_sage_field_diasentreplazos = fields.Char(required = False, string = '_sage_field_diasentreplazos')
	_sage_field_diasfijos1 = fields.Char(required = False, string = '_sage_field_diasfijos1')
	_sage_field_diasfijos2 = fields.Char(required = False, string = '_sage_field_diasfijos2')
	_sage_field_diasfijos3 = fields.Char(required = False, string = '_sage_field_diasfijos3')
	_sage_field_inicionopago = fields.Char(required = False, string = '_sage_field_inicionopago')
	_sage_field_finnopago = fields.Char(required = False, string = '_sage_field_finnopago')
	_sage_field_controlarfestivos = fields.Char(required = False, string = '_sage_field_controlarfestivos')
	_sage_field_diasretroceso = fields.Char(required = False, string = '_sage_field_diasretroceso')
	_sage_field_mesescomerciales = fields.Char(required = False, string = '_sage_field_mesescomerciales')
	_sage_field_codigocontable = fields.Char(required = False, string = '_sage_field_codigocontable')
	_sage_field_codigodefinicion = fields.Char(required = False, string = '_sage_field_codigodefinicion')
	_sage_field_remesahabitual = fields.Char(required = False, string = '_sage_field_remesahabitual')
	_sage_field_codigobanco = fields.Char(required = False, string = '_sage_field_codigobanco')
	_sage_field_codigoagencia = fields.Char(required = False, string = '_sage_field_codigoagencia')
	_sage_field_dc = fields.Char(required = False, string = '_sage_field_dc')
	_sage_field_ccc = fields.Char(required = False, string = '_sage_field_ccc')
	_sage_field_iban = fields.Char(required = False, string = '_sage_field_iban')
	_sage_field_domicilioenvio = fields.Char(required = False, string = '_sage_field_domicilioenvio')
	_sage_field_domiciliofactura = fields.Char(required = False, string = '_sage_field_domiciliofactura')
	_sage_field_domiciliorecibo = fields.Char(required = False, string = '_sage_field_domiciliorecibo')
	_sage_field_codigoproyecto = fields.Char(required = False, string = '_sage_field_codigoproyecto')
	_sage_field_codigoseccion = fields.Char(required = False, string = '_sage_field_codigoseccion')
	_sage_field_codigodepartamento = fields.Char(required = False, string = '_sage_field_codigodepartamento')
	_sage_field_codigotransportistaenvios = fields.Char(required = False, string = '_sage_field_codigotransportistaenvios')
	_sage_field_tipoportesenvios = fields.Char(required = False, string = '_sage_field_tipoportesenvios')
	_sage_field_codigoretencion = fields.Char(required = False, string = '_sage_field_codigoretencion')
	_sage_field_codigotransaccion = fields.Char(required = False, string = '_sage_field_codigotransaccion')
	_sage_field_codigozona = fields.Char(required = False, string = '_sage_field_codigozona')
	_sage_field_codigocanal = fields.Char(required = False, string = '_sage_field_codigocanal')
	_sage_field_codigoruta = fields.Char(required = False, string = '_sage_field_codigoruta')
	_sage_field_codigoterritorio = fields.Char(required = False, string = '_sage_field_codigoterritorio')
	_sage_field_codigotipoefecto = fields.Char(required = False, string = '_sage_field_codigotipoefecto')
	_sage_field_codigoexportacion = fields.Char(required = False, string = '_sage_field_codigoexportacion')
	_sage_field_condicionexportacion = fields.Char(required = False, string = '_sage_field_condicionexportacion')
	_sage_field_tarifaprecio = fields.Char(required = False, string = '_sage_field_tarifaprecio')
	_sage_field_tarifadescuento = fields.Char(required = False, string = '_sage_field_tarifadescuento')
	_sage_field_grupoiva = fields.Char(required = False, string = '_sage_field_grupoiva')
	_sage_field_indicadoriva = fields.Char(required = False, string = '_sage_field_indicadoriva')
	_sage_field_ivaincluido = fields.Char(required = False, string = '_sage_field_ivaincluido')
	_sage_field_servircompleto = fields.Char(required = False, string = '_sage_field_servircompleto')
	_sage_field_reservarstock = fields.Char(required = False, string = '_sage_field_reservarstock')
	_sage_field_estado = fields.Char(required = False, string = '_sage_field_estado')
	_sage_field_statusanalitica = fields.Char(required = False, string = '_sage_field_statusanalitica')
	_sage_field_statusaprobado = fields.Char(required = False, string = '_sage_field_statusaprobado')
	_sage_field_statuslistado = fields.Char(required = False, string = '_sage_field_statuslistado')
	_sage_field_statusestadis = fields.Char(required = False, string = '_sage_field_statusestadis')
	_sage_field_percent_descuento = fields.Char(required = False, string = '_sage_field_percent_descuento')
	_sage_field_percent_prontopago = fields.Char(required = False, string = '_sage_field_percent_prontopago')
	_sage_field_percent_financiacion = fields.Char(required = False, string = '_sage_field_percent_financiacion')
	_sage_field_percent_retencion = fields.Char(required = False, string = '_sage_field_percent_retencion')
	_sage_field_percent_rappel = fields.Char(required = False, string = '_sage_field_percent_rappel')
	_sage_field_codigocomisionista = fields.Char(required = False, string = '_sage_field_codigocomisionista')
	_sage_field_codigocomisionista2 = fields.Char(required = False, string = '_sage_field_codigocomisionista2')
	_sage_field_codigocomisionista3 = fields.Char(required = False, string = '_sage_field_codigocomisionista3')
	_sage_field_codigocomisionista4 = fields.Char(required = False, string = '_sage_field_codigocomisionista4')
	_sage_field_codigojefeventa = fields.Char(required = False, string = '_sage_field_codigojefeventa')
	_sage_field_codigojefezona = fields.Char(required = False, string = '_sage_field_codigojefezona')
	_sage_field_percent_comision = fields.Char(required = False, string = '_sage_field_percent_comision')
	_sage_field_percent_comision2 = fields.Char(required = False, string = '_sage_field_percent_comision2')
	_sage_field_percent_comision3 = fields.Char(required = False, string = '_sage_field_percent_comision3')
	_sage_field_percent_comision4 = fields.Char(required = False, string = '_sage_field_percent_comision4')
	_sage_field_comisionsobreventa_percent = fields.Char(required = False, string = '_sage_field_comisionsobreventa_percent')
	_sage_field_comisionsobrezona_percent = fields.Char(required = False, string = '_sage_field_comisionsobrezona_percent')
	_sage_field_periodicidadfacturas = fields.Char(required = False, string = '_sage_field_periodicidadfacturas')
	_sage_field_mascarapedido = fields.Char(required = False, string = '_sage_field_mascarapedido')
	_sage_field_agruparalbaranes = fields.Char(required = False, string = '_sage_field_agruparalbaranes')
	_sage_field_albaranvalorado = fields.Char(required = False, string = '_sage_field_albaranvalorado')
	_sage_field_copiasalbaran = fields.Char(required = False, string = '_sage_field_copiasalbaran')
	_sage_field_copiasfactura = fields.Char(required = False, string = '_sage_field_copiasfactura')
	_sage_field_copiaspedido = fields.Char(required = False, string = '_sage_field_copiaspedido')
	_sage_field_observacionescliente = fields.Char(required = False, string = '_sage_field_observacionescliente')
	_sage_field_observacionespedido = fields.Char(required = False, string = '_sage_field_observacionespedido')
	_sage_field_observacionesalbaran = fields.Char(required = False, string = '_sage_field_observacionesalbaran')
	_sage_field_observacionesfactura = fields.Char(required = False, string = '_sage_field_observacionesfactura')
	_sage_field_supedido = fields.Char(required = False, string = '_sage_field_supedido')
	_sage_field_fechanecesaria = fields.Char(required = False, string = '_sage_field_fechanecesaria')
	_sage_field_fechaentrega = fields.Char(required = False, string = '_sage_field_fechaentrega')
	_sage_field_fechatope = fields.Char(required = False, string = '_sage_field_fechatope')
	_sage_field_pesobruto = fields.Char(required = False, string = '_sage_field_pesobruto')
	_sage_field_pesoneto = fields.Char(required = False, string = '_sage_field_pesoneto')
	_sage_field_volumen = fields.Char(required = False, string = '_sage_field_volumen')
	_sage_field_eneuros = fields.Char(required = False, string = '_sage_field_eneuros')
	_sage_field_codigodivisa = fields.Char(required = False, string = '_sage_field_codigodivisa')
	_sage_field_codigoidioma = fields.Char(required = False, string = '_sage_field_codigoidioma')
	_sage_field_mantenercambio = fields.Char(required = False, string = '_sage_field_mantenercambio')
	_sage_field_factorcambio = fields.Char(required = False, string = '_sage_field_factorcambio')
	_sage_field_importecambio = fields.Char(required = False, string = '_sage_field_importecambio')
	_sage_field_importecambioviejo = fields.Char(required = False, string = '_sage_field_importecambioviejo')
	_sage_field_importecoste = fields.Char(required = False, string = '_sage_field_importecoste')
	_sage_field_importebruto = fields.Char(required = False, string = '_sage_field_importebruto')
	_sage_field_importebrutodivisa = fields.Char(required = False, string = '_sage_field_importebrutodivisa')
	_sage_field_importebrutopendiente = fields.Char(required = False, string = '_sage_field_importebrutopendiente')
	_sage_field_importedescuentolineas = fields.Char(required = False, string = '_sage_field_importedescuentolineas')
	_sage_field_importedtolineasdivisa = fields.Char(required = False, string = '_sage_field_importedtolineasdivisa')
	_sage_field_importenetolineas = fields.Char(required = False, string = '_sage_field_importenetolineas')
	_sage_field_importenetolineasdivisa = fields.Char(required = False, string = '_sage_field_importenetolineasdivisa')
	_sage_field_importenetolineaspendiente = fields.Char(required = False, string = '_sage_field_importenetolineaspendiente')
	_sage_field_importedescuento = fields.Char(required = False, string = '_sage_field_importedescuento')
	_sage_field_importedescuentodivisa = fields.Char(required = False, string = '_sage_field_importedescuentodivisa')
	_sage_field_importeparcial = fields.Char(required = False, string = '_sage_field_importeparcial')
	_sage_field_importeparcialdivisa = fields.Char(required = False, string = '_sage_field_importeparcialdivisa')
	_sage_field_importeparcialpendiente = fields.Char(required = False, string = '_sage_field_importeparcialpendiente')
	_sage_field_importeprontopago = fields.Char(required = False, string = '_sage_field_importeprontopago')
	_sage_field_importeprontopagodivisa = fields.Char(required = False, string = '_sage_field_importeprontopagodivisa')
	_sage_field_baseimponible = fields.Char(required = False, string = '_sage_field_baseimponible')
	_sage_field_baseimponibledivisa = fields.Char(required = False, string = '_sage_field_baseimponibledivisa')
	_sage_field_baseimponiblependiente = fields.Char(required = False, string = '_sage_field_baseimponiblependiente')
	_sage_field_totalcuotaiva = fields.Char(required = False, string = '_sage_field_totalcuotaiva')
	_sage_field_totalcuotaivadivisa = fields.Char(required = False, string = '_sage_field_totalcuotaivadivisa')
	_sage_field_totalcuotarecargo = fields.Char(required = False, string = '_sage_field_totalcuotarecargo')
	_sage_field_totalcuotarecargodivisa = fields.Char(required = False, string = '_sage_field_totalcuotarecargodivisa')
	_sage_field_totaliva = fields.Char(required = False, string = '_sage_field_totaliva')
	_sage_field_totalivadivisa = fields.Char(required = False, string = '_sage_field_totalivadivisa')
	_sage_field_importefinanciacion = fields.Char(required = False, string = '_sage_field_importefinanciacion')
	_sage_field_importefinanciaciondivisa = fields.Char(required = False, string = '_sage_field_importefinanciaciondivisa')
	_sage_field_importeliquido = fields.Char(required = False, string = '_sage_field_importeliquido')
	_sage_field_importeliquidodivisa = fields.Char(required = False, string = '_sage_field_importeliquidodivisa')
	_sage_field_importerappel = fields.Char(required = False, string = '_sage_field_importerappel')
	_sage_field_importerappeldivisa = fields.Char(required = False, string = '_sage_field_importerappeldivisa')
	_sage_field_ejerciciofacturaoriginal = fields.Char(required = False, string = '_sage_field_ejerciciofacturaoriginal')
	_sage_field_seriefacturaoriginal = fields.Char(required = False, string = '_sage_field_seriefacturaoriginal')
	_sage_field_numerofacturaoriginal = fields.Char(required = False, string = '_sage_field_numerofacturaoriginal')
	_sage_field_ejerciciooferta = fields.Char(required = False, string = '_sage_field_ejerciciooferta')
	_sage_field_serieoferta = fields.Char(required = False, string = '_sage_field_serieoferta')
	_sage_field_numerooferta = fields.Char(required = False, string = '_sage_field_numerooferta')
	_sage_field_codigotipooperacionlc = fields.Char(required = False, string = '_sage_field_codigotipooperacionlc')
	_sage_field_codigotipooperacionorigenlc = fields.Char(required = False, string = '_sage_field_codigotipooperacionorigenlc')
	_sage_field_codigodivisionlc = fields.Char(required = False, string = '_sage_field_codigodivisionlc')
	_sage_field_codigoambitoclientelc = fields.Char(required = False, string = '_sage_field_codigoambitoclientelc')
	_sage_field_codigoclaseclientelc = fields.Char(required = False, string = '_sage_field_codigoclaseclientelc')
	_sage_field_codigosubclaseclientelc = fields.Char(required = False, string = '_sage_field_codigosubclaseclientelc')
	_sage_field_codigotipoclientelc = fields.Char(required = False, string = '_sage_field_codigotipoclientelc')
	_sage_field_codigogrupoclientelc = fields.Char(required = False, string = '_sage_field_codigogrupoclientelc')
	_sage_field_codigoactividadlc = fields.Char(required = False, string = '_sage_field_codigoactividadlc')
	_sage_field_codigosubactividadlc = fields.Char(required = False, string = '_sage_field_codigosubactividadlc')
	_sage_field_comercialasignadolc = fields.Char(required = False, string = '_sage_field_comercialasignadolc')
	_sage_field_facturarcompletolc = fields.Char(required = False, string = '_sage_field_facturarcompletolc')
	_sage_field_idfacturarcompletolc = fields.Char(required = False, string = '_sage_field_idfacturarcompletolc')
	_sage_field_idfacturacionconjuntalc = fields.Char(required = False, string = '_sage_field_idfacturacionconjuntalc')
	_sage_field_iddelegacioncentrallc = fields.Char(required = False, string = '_sage_field_iddelegacioncentrallc')
	_sage_field_codigocampanalc = fields.Char(required = False, string = '_sage_field_codigocampanalc')
	_sage_field_referenciaedi = fields.Char(required = False, string = '_sage_field_referenciaedi')
	_sage_field_codigomotivoabonolc = fields.Char(required = False, string = '_sage_field_codigomotivoabonolc')
	_sage_field_ejercicioalbaranoriginallc = fields.Char(required = False, string = '_sage_field_ejercicioalbaranoriginallc')
	_sage_field_seriealbaranoriginallc = fields.Char(required = False, string = '_sage_field_seriealbaranoriginallc')
	_sage_field_numeroalbaranoriginallc = fields.Char(required = False, string = '_sage_field_numeroalbaranoriginallc')
	_sage_field_generarfactura = fields.Char(required = False, string = '_sage_field_generarfactura')
	_sage_field_importeacuentap = fields.Char(required = False, string = '_sage_field_importeacuentap')
	_sage_field_importeacuentapdivisa = fields.Char(required = False, string = '_sage_field_importeacuentapdivisa')
	_sage_field_importeconsumidop = fields.Char(required = False, string = '_sage_field_importeconsumidop')
	_sage_field_importeconsumidopdivisa = fields.Char(required = False, string = '_sage_field_importeconsumidopdivisa')
	_sage_field_ejercicioalbarandevolucionp = fields.Char(required = False, string = '_sage_field_ejercicioalbarandevolucionp')
	_sage_field_seriealbarandevolucionp = fields.Char(required = False, string = '_sage_field_seriealbarandevolucionp')
	_sage_field_numeroalbarandevolucionp = fields.Char(required = False, string = '_sage_field_numeroalbarandevolucionp')
	_sage_field_importependientepac = fields.Char(required = False, string = '_sage_field_importependientepac')
	_sage_field_importependientepacdivisa = fields.Char(required = False, string = '_sage_field_importependientepacdivisa')
	_sage_field_importefactura = fields.Char(required = False, string = '_sage_field_importefactura')
	_sage_field_importefacturadivisa = fields.Char(required = False, string = '_sage_field_importefacturadivisa')
	_sage_field_pormargenbeneficio = fields.Char(required = False, string = '_sage_field_pormargenbeneficio')
	_sage_field_margenbeneficio = fields.Char(required = False, string = '_sage_field_margenbeneficio')
	_sage_field_ejercicioexpediente = fields.Char(required = False, string = '_sage_field_ejercicioexpediente')
	_sage_field_serieexpediente = fields.Char(required = False, string = '_sage_field_serieexpediente')
	_sage_field_numeroexpediente = fields.Char(required = False, string = '_sage_field_numeroexpediente')
	_sage_field_origendespacho = fields.Char(required = False, string = '_sage_field_origendespacho')
	_sage_field_importeprovisiones = fields.Char(required = False, string = '_sage_field_importeprovisiones')
	_sage_field_importeprovisionesnf = fields.Char(required = False, string = '_sage_field_importeprovisionesnf')
	_sage_field_importesuplidos = fields.Char(required = False, string = '_sage_field_importesuplidos')
	_sage_field_importeprovisionesdivisa = fields.Char(required = False, string = '_sage_field_importeprovisionesdivisa')
	_sage_field_importeprovisionesnfdivisa = fields.Char(required = False, string = '_sage_field_importeprovisionesnfdivisa')
	_sage_field_importesuplidosdivisa = fields.Char(required = False, string = '_sage_field_importesuplidosdivisa')
	_sage_field_codigocontableant = fields.Char(required = False, string = '_sage_field_codigocontableant')
	_sage_field_remesahabitualant = fields.Char(required = False, string = '_sage_field_remesahabitualant')
	_sage_field_analote = fields.Char(required = False, string = '_sage_field_analote')
	_sage_field_anacapitulo = fields.Char(required = False, string = '_sage_field_anacapitulo')
	_sage_field_nofacturable = fields.Char(required = False, string = '_sage_field_nofacturable')
	_sage_field_observacionesweb = fields.Char(required = False, string = '_sage_field_observacionesweb')
	_sage_field_supedidoweb = fields.Char(required = False, string = '_sage_field_supedidoweb')
	_sage_field_varfechatraspaso = fields.Char(required = False, string = '_sage_field_varfechatraspaso')
	_sage_field_vartraspasado = fields.Char(required = False, string = '_sage_field_vartraspasado')
	_sage_field_idpedidocli = fields.Char(required = False, string = '_sage_field_idpedidocli')
	_sage_field_referenciamandato = fields.Char(required = False, string = '_sage_field_referenciamandato')
	_sage_field_comentarios = fields.Char(required = False, string = '_sage_field_comentarios')
	_sage_field_sucontrato = fields.Char(required = False, string = '_sage_field_sucontrato')
	_sage_field_s_aplicarbaremost = fields.Char(required = False, string = '_sage_field_s_aplicarbaremost')
	_sage_field_s_usuariocrea = fields.Char(required = False, string = '_sage_field_s_usuariocrea')
	_sage_field_s_nombreusuario = fields.Char(required = False, string = '_sage_field_s_nombreusuario')
	_sage_field_sumex_pedidoaservir = fields.Char(required = False, string = '_sage_field_sumex_pedidoaservir')
	_sage_field_cp_ediemisor = fields.Char(required = False, string = '_sage_field_cp_ediemisor')
	_sage_field_cp_edivendedor = fields.Char(required = False, string = '_sage_field_cp_edivendedor')
	_sage_field_cp_edicomprador = fields.Char(required = False, string = '_sage_field_cp_edicomprador')
	_sage_field_cp_edi = fields.Char(required = False, string = '_sage_field_cp_edi')
	_sage_field_cp_fechaentini = fields.Char(required = False, string = '_sage_field_cp_fechaentini')
	_sage_field_cp_fechaentfin = fields.Char(required = False, string = '_sage_field_cp_fechaentfin')
	_sage_field_cp_librevar1 = fields.Char(required = False, string = '_sage_field_cp_librevar1')
	_sage_field_cp_librevar2 = fields.Char(required = False, string = '_sage_field_cp_librevar2')
	_sage_field_cp_preciotransporte = fields.Char(required = False, string = '_sage_field_cp_preciotransporte')
	_sage_field_sumex_codigorecargo = fields.Char(required = False, string = '_sage_field_sumex_codigorecargo')
	_sage_field_sumex_importerecargo = fields.Char(required = False, string = '_sage_field_sumex_importerecargo')
	_sage_field_sumex_porrecargo = fields.Char(required = False, string = '_sage_field_sumex_porrecargo')
	_sage_field_pagoinmediato = fields.Char(required = False, string = '_sage_field_pagoinmediato')
	_sage_field_statuswf = fields.Char(required = False, string = '_sage_field_statuswf')

	@api.model
	def create(self, vals_list):

		if 'from_import_csv_name' not in self._context or self._context['from_import_csv_name'] != 'sumex_apps_imports_csv_import_sage_ventas_cabeceras':
			return super(sumex_apps_sage_inherits_sage_sale_order_inherit, self).create(vals_list)
		vals_list['_created_from_sumex_apps_imports_csv_of_sage_ventas'] = True
		rows = super(sumex_apps_sage_inherits_sage_sale_order_inherit, self).create(vals_list)
		return rows

	def write(self, vals_list):

		if 'from_import_csv_name' not in self._context or self._context['from_import_csv_name'] != 'sumex_apps_imports_csv_import_sage_ventas_cabeceras':
			return super(sumex_apps_sage_inherits_sage_sale_order_inherit, self).write(vals_list)
		vals_list['_created_from_sumex_apps_imports_csv_of_sage_ventas'] = True
		rows = super(sumex_apps_sage_inherits_sage_sale_order_inherit, self).write(vals_list)
		return rows
