# -*- coding: utf-8 -*-

from odoo import models, fields, api


class sumex_apps_sage_inherits_sage_product_inherit(models.Model):

	_inherit = 'product.template'

	_created_from_sumex_apps_imports_csv_of_sage = fields.Boolean("From import CSV of Sage", required = False)

	_sage_field_codigoempresa = fields.Char(required = False, string = '_sage_field_codigoempresa')
	_sage_field_codigoarticulo = fields.Char(required = False, string = '_sage_field_codigoarticulo')
	_sage_field_descripcionarticulo = fields.Char(required = False, string = '_sage_field_descripcionarticulo')
	_sage_field_descripcion2articulo = fields.Char(required = False, string = '_sage_field_descripcion2articulo')
	_sage_field_descripcionlinea = fields.Char(required = False, string = '_sage_field_descripcionlinea')
	_sage_field_comentarioarticulo = fields.Char(required = False, string = '_sage_field_comentarioarticulo')
	_sage_field_marcaproducto = fields.Char(required = False, string = '_sage_field_marcaproducto')
	_sage_field_codigoalternativo = fields.Char(required = False, string = '_sage_field_codigoalternativo')
	_sage_field_codigoalternativo2 = fields.Char(required = False, string = '_sage_field_codigoalternativo2')
	_sage_field_codigoarticulooferta = fields.Char(required = False, string = '_sage_field_codigoarticulooferta')
	_sage_field_codigoarancelario = fields.Char(required = False, string = '_sage_field_codigoarancelario')
	_sage_field_codigoproveedor = fields.Char(required = False, string = '_sage_field_codigoproveedor')
	_sage_field_referenciaedi_ = fields.Char(required = False, string = '_sage_field_referenciaedi_')
	_sage_field_publicarinternet = fields.Char(required = False, string = '_sage_field_publicarinternet')
	_sage_field_tipoarticulo = fields.Char(required = False, string = '_sage_field_tipoarticulo')
	_sage_field_utilizado = fields.Char(required = False, string = '_sage_field_utilizado')
	_sage_field_fechaalta = fields.Char(required = False, string = '_sage_field_fechaalta')
	_sage_field_fechainiciooferta = fields.Char(required = False, string = '_sage_field_fechainiciooferta')
	_sage_field_fechafinaloferta = fields.Char(required = False, string = '_sage_field_fechafinaloferta')
	_sage_field_temporada = fields.Char(required = False, string = '_sage_field_temporada')
	_sage_field_tipoenvase_ = fields.Char(required = False, string = '_sage_field_tipoenvase_')
	_sage_field_unidadmedida2_ = fields.Char(required = False, string = '_sage_field_unidadmedida2_')
	_sage_field_unidadmedidaalternativa_ = fields.Char(required = False, string = '_sage_field_unidadmedidaalternativa_')
	_sage_field_factorconversion_ = fields.Char(required = False, string = '_sage_field_factorconversion_')
	_sage_field_codigofamilia = fields.Char(required = False, string = '_sage_field_codigofamilia')
	_sage_field_codigosubfamilia = fields.Char(required = False, string = '_sage_field_codigosubfamilia')
	_sage_field_codigodivisa = fields.Char(required = False, string = '_sage_field_codigodivisa')
	_sage_field_codigoproyecto = fields.Char(required = False, string = '_sage_field_codigoproyecto')
	_sage_field_codigoseccion = fields.Char(required = False, string = '_sage_field_codigoseccion')
	_sage_field_codigodepartamento = fields.Char(required = False, string = '_sage_field_codigodepartamento')
	_sage_field_codigodefinicion_ = fields.Char(required = False, string = '_sage_field_codigodefinicion_')
	_sage_field_valoracionstock = fields.Char(required = False, string = '_sage_field_valoracionstock')
	_sage_field_tratamientopartidas = fields.Char(required = False, string = '_sage_field_tratamientopartidas')
	_sage_field_contadorpartida = fields.Char(required = False, string = '_sage_field_contadorpartida')
	_sage_field_colores_ = fields.Char(required = False, string = '_sage_field_colores_')
	_sage_field_grupotalla_ = fields.Char(required = False, string = '_sage_field_grupotalla_')
	_sage_field_acumulaestadistica_ = fields.Char(required = False, string = '_sage_field_acumulaestadistica_')
	_sage_field_generacompraautomatica_ = fields.Char(required = False, string = '_sage_field_generacompraautomatica_')
	_sage_field_ivaincluido = fields.Char(required = False, string = '_sage_field_ivaincluido')
	_sage_field_bloqueocompra = fields.Char(required = False, string = '_sage_field_bloqueocompra')
	_sage_field_bloqueopedidocompra = fields.Char(required = False, string = '_sage_field_bloqueopedidocompra')
	_sage_field_bloqueoalbaranventa = fields.Char(required = False, string = '_sage_field_bloqueoalbaranventa')
	_sage_field_bloqueopedidoventa = fields.Char(required = False, string = '_sage_field_bloqueopedidoventa')
	_sage_field_unidadesminimasoferta = fields.Char(required = False, string = '_sage_field_unidadesminimasoferta')
	_sage_field_unidadesregalooferta = fields.Char(required = False, string = '_sage_field_unidadesregalooferta')
	_sage_field_stockminimo = fields.Char(required = False, string = '_sage_field_stockminimo')
	_sage_field_stockmaximo = fields.Char(required = False, string = '_sage_field_stockmaximo')
	_sage_field_puntopedido = fields.Char(required = False, string = '_sage_field_puntopedido')
	_sage_field_lotepedido = fields.Char(required = False, string = '_sage_field_lotepedido')
	_sage_field_grupoiva = fields.Char(required = False, string = '_sage_field_grupoiva')
	_sage_field_grupoivacompras = fields.Char(required = False, string = '_sage_field_grupoivacompras')
	_sage_field_preciocompra = fields.Char(required = False, string = '_sage_field_preciocompra')
	_sage_field_precioventa = fields.Char(required = False, string = '_sage_field_precioventa')
	_sage_field_percent_margen = fields.Char(required = False, string = '_sage_field_percent_margen')
	_sage_field_costefabricacionunitario = fields.Char(required = False, string = '_sage_field_costefabricacionunitario')
	_sage_field_preciocosteestandar = fields.Char(required = False, string = '_sage_field_preciocosteestandar')
	_sage_field_precioventaconiva1 = fields.Char(required = False, string = '_sage_field_precioventaconiva1')
	_sage_field_precioventaconiva2 = fields.Char(required = False, string = '_sage_field_precioventaconiva2')
	_sage_field_precioventaconiva3 = fields.Char(required = False, string = '_sage_field_precioventaconiva3')
	_sage_field_precioventasiniva1 = fields.Char(required = False, string = '_sage_field_precioventasiniva1')
	_sage_field_precioventasiniva2 = fields.Char(required = False, string = '_sage_field_precioventasiniva2')
	_sage_field_precioventasiniva3 = fields.Char(required = False, string = '_sage_field_precioventasiniva3')
	_sage_field_precioofertaconiva = fields.Char(required = False, string = '_sage_field_precioofertaconiva')
	_sage_field_precioofertasiniva = fields.Char(required = False, string = '_sage_field_precioofertasiniva')
	_sage_field_percent_descuento = fields.Char(required = False, string = '_sage_field_percent_descuento')
	_sage_field_percent_descuento2 = fields.Char(required = False, string = '_sage_field_percent_descuento2')
	_sage_field_percent_descuento3 = fields.Char(required = False, string = '_sage_field_percent_descuento3')
	_sage_field_percent_descuentocompras = fields.Char(required = False, string = '_sage_field_percent_descuentocompras')
	_sage_field_percent_descuentocompras2 = fields.Char(required = False, string = '_sage_field_percent_descuentocompras2')
	_sage_field_percent_descuentocompras3 = fields.Char(required = False, string = '_sage_field_percent_descuentocompras3')
	_sage_field_descuentooferta = fields.Char(required = False, string = '_sage_field_descuentooferta')
	_sage_field_aplicardescuentos = fields.Char(required = False, string = '_sage_field_aplicardescuentos')
	_sage_field_codigocomisionista = fields.Char(required = False, string = '_sage_field_codigocomisionista')
	_sage_field_codigocomisionista2_ = fields.Char(required = False, string = '_sage_field_codigocomisionista2_')
	_sage_field_codigocomisionista3_ = fields.Char(required = False, string = '_sage_field_codigocomisionista3_')
	_sage_field_codigocomisionista4_ = fields.Char(required = False, string = '_sage_field_codigocomisionista4_')
	_sage_field_percent_comision = fields.Char(required = False, string = '_sage_field_percent_comision')
	_sage_field_percent_comision2_ = fields.Char(required = False, string = '_sage_field_percent_comision2_')
	_sage_field_percent_comision3_ = fields.Char(required = False, string = '_sage_field_percent_comision3_')
	_sage_field_percent_comision4_ = fields.Char(required = False, string = '_sage_field_percent_comision4_')
	_sage_field_pesobrutounitario_ = fields.Char(required = False, string = '_sage_field_pesobrutounitario_')
	_sage_field_pesonetounitario_ = fields.Char(required = False, string = '_sage_field_pesonetounitario_')
	_sage_field_volumenunitario_ = fields.Char(required = False, string = '_sage_field_volumenunitario_')
	_sage_field_formulalote = fields.Char(required = False, string = '_sage_field_formulalote')
	_sage_field_lote_ = fields.Char(required = False, string = '_sage_field_lote_')
	_sage_field_formula = fields.Char(required = False, string = '_sage_field_formula')
	_sage_field_lotefabricacion = fields.Char(required = False, string = '_sage_field_lotefabricacion')
	_sage_field_nivelcompuesto = fields.Char(required = False, string = '_sage_field_nivelcompuesto')
	_sage_field_tipodemanda = fields.Char(required = False, string = '_sage_field_tipodemanda')
	_sage_field_generarplanprod = fields.Char(required = False, string = '_sage_field_generarplanprod')
	_sage_field_usarstockseg = fields.Char(required = False, string = '_sage_field_usarstockseg')
	_sage_field_percent_stockseguridad = fields.Char(required = False, string = '_sage_field_percent_stockseguridad')
	_sage_field_demandamediadiaria = fields.Char(required = False, string = '_sage_field_demandamediadiaria')
	_sage_field_factorcrecimiento = fields.Char(required = False, string = '_sage_field_factorcrecimiento')
	_sage_field_periodospromediar = fields.Char(required = False, string = '_sage_field_periodospromediar')
	_sage_field_tasaproducciondiaria = fields.Char(required = False, string = '_sage_field_tasaproducciondiaria')
	_sage_field_tiempomedioreposicion = fields.Char(required = False, string = '_sage_field_tiempomedioreposicion')
	_sage_field_numdecimalesunidades = fields.Char(required = False, string = '_sage_field_numdecimalesunidades')
	_sage_field_periodovida = fields.Char(required = False, string = '_sage_field_periodovida')
	_sage_field_tipoabc = fields.Char(required = False, string = '_sage_field_tipoabc')
	_sage_field_codigocategorialc = fields.Char(required = False, string = '_sage_field_codigocategorialc')
	_sage_field_codigosubcategorialc = fields.Char(required = False, string = '_sage_field_codigosubcategorialc')
	_sage_field_codigoclasearticulolc = fields.Char(required = False, string = '_sage_field_codigoclasearticulolc')
	_sage_field_codigotipoarticulolc = fields.Char(required = False, string = '_sage_field_codigotipoarticulolc')
	_sage_field_codigosubtipoarticulolc = fields.Char(required = False, string = '_sage_field_codigosubtipoarticulolc')
	_sage_field_codigogrupoarticulolc = fields.Char(required = False, string = '_sage_field_codigogrupoarticulolc')
	_sage_field_codigosubgrupoarticulolc = fields.Char(required = False, string = '_sage_field_codigosubgrupoarticulolc')
	_sage_field_codigomodolc = fields.Char(required = False, string = '_sage_field_codigomodolc')
	_sage_field_codigofabricantelc = fields.Char(required = False, string = '_sage_field_codigofabricantelc')
	_sage_field_codigofamiliafabricantelc = fields.Char(required = False, string = '_sage_field_codigofamiliafabricantelc')
	_sage_field_codigoconjuntolc = fields.Char(required = False, string = '_sage_field_codigoconjuntolc')
	_sage_field_codigosubconjuntolc = fields.Char(required = False, string = '_sage_field_codigosubconjuntolc')
	_sage_field_maximosinretencionlc = fields.Char(required = False, string = '_sage_field_maximosinretencionlc')
	_sage_field_tratanumerosserielc = fields.Char(required = False, string = '_sage_field_tratanumerosserielc')
	_sage_field_sonhoraslc = fields.Char(required = False, string = '_sage_field_sonhoraslc')
	_sage_field_articulonocodificadolc = fields.Char(required = False, string = '_sage_field_articulonocodificadolc')
	_sage_field_preciocosteeditablelc = fields.Char(required = False, string = '_sage_field_preciocosteeditablelc')
	_sage_field_codigotipoperiodicidadpreciolc = fields.Char(required = False, string = '_sage_field_codigotipoperiodicidadpreciolc')
	_sage_field_liquidablelc = fields.Char(required = False, string = '_sage_field_liquidablelc')
	_sage_field_codigotipocoberturalc = fields.Char(required = False, string = '_sage_field_codigotipocoberturalc')
	_sage_field_obsoletolc = fields.Char(required = False, string = '_sage_field_obsoletolc')
	_sage_field_codigoareacompetencialc = fields.Char(required = False, string = '_sage_field_codigoareacompetencialc')
	_sage_field_imagenext = fields.Char(required = False, string = '_sage_field_imagenext')
	_sage_field_gestioncompras = fields.Char(required = False, string = '_sage_field_gestioncompras')
	_sage_field_unidadmedidacompras_ = fields.Char(required = False, string = '_sage_field_unidadmedidacompras_')
	_sage_field_unidadmedidaventas_ = fields.Char(required = False, string = '_sage_field_unidadmedidaventas_')
	_sage_field_unidadmedidafabricacion_ = fields.Char(required = False, string = '_sage_field_unidadmedidafabricacion_')
	_sage_field_codigoserie = fields.Char(required = False, string = '_sage_field_codigoserie')
	_sage_field_unidadmedidaserie = fields.Char(required = False, string = '_sage_field_unidadmedidaserie')
	_sage_field_factorpreciocompra_ = fields.Char(required = False, string = '_sage_field_factorpreciocompra_')
	_sage_field_factorprecioventa_ = fields.Char(required = False, string = '_sage_field_factorprecioventa_')
	_sage_field_tipounidadcalculo_ = fields.Char(required = False, string = '_sage_field_tipounidadcalculo_')
	_sage_field_medida = fields.Char(required = False, string = '_sage_field_medida')
	_sage_field_tipoarticulopresupuesto = fields.Char(required = False, string = '_sage_field_tipoarticulopresupuesto')
	_sage_field_tipocodificado = fields.Char(required = False, string = '_sage_field_tipocodificado')
	_sage_field_codigoperiodicidadprecio = fields.Char(required = False, string = '_sage_field_codigoperiodicidadprecio')
	_sage_field_cobrardevoluciontardia = fields.Char(required = False, string = '_sage_field_cobrardevoluciontardia')
	_sage_field_cobrarentregaadelantada = fields.Char(required = False, string = '_sage_field_cobrarentregaadelantada')
	_sage_field_devolverdevolucionadelantada = fields.Char(required = False, string = '_sage_field_devolverdevolucionadelantada')
	_sage_field_devolverentregatardia = fields.Char(required = False, string = '_sage_field_devolverentregatardia')
	_sage_field_codigoarticulofacturacion = fields.Char(required = False, string = '_sage_field_codigoarticulofacturacion')
	_sage_field_precioperiodoretraso = fields.Char(required = False, string = '_sage_field_precioperiodoretraso')
	_sage_field_preciounidadperdida = fields.Char(required = False, string = '_sage_field_preciounidadperdida')
	_sage_field_partirperiodos = fields.Char(required = False, string = '_sage_field_partirperiodos')
	_sage_field_tipoarticuloalquiler = fields.Char(required = False, string = '_sage_field_tipoarticuloalquiler')
	_sage_field_notraspasarsfa = fields.Char(required = False, string = '_sage_field_notraspasarsfa')
	_sage_field_codigocontaje = fields.Char(required = False, string = '_sage_field_codigocontaje')
	_sage_field_precioportramos = fields.Char(required = False, string = '_sage_field_precioportramos')
	_sage_field_suplido = fields.Char(required = False, string = '_sage_field_suplido')
	_sage_field_codigonacionorigen = fields.Char(required = False, string = '_sage_field_codigonacionorigen')
	_sage_field_tipocodigobarrassr = fields.Char(required = False, string = '_sage_field_tipocodigobarrassr')
	_sage_field_pesablesr = fields.Char(required = False, string = '_sage_field_pesablesr')
	_sage_field_imagentactilsr = fields.Char(required = False, string = '_sage_field_imagentactilsr')
	_sage_field_taraunitaria_ = fields.Char(required = False, string = '_sage_field_taraunitaria_')
	_sage_field_preciomodificablesr = fields.Char(required = False, string = '_sage_field_preciomodificablesr')
	_sage_field_noagruparsr = fields.Char(required = False, string = '_sage_field_noagruparsr')
	_sage_field_enviarasr = fields.Char(required = False, string = '_sage_field_enviarasr')
	_sage_field_impresionresguardosr = fields.Char(required = False, string = '_sage_field_impresionresguardosr')
	_sage_field_periodogarantiasr = fields.Char(required = False, string = '_sage_field_periodogarantiasr')
	_sage_field_novedadesweb = fields.Char(required = False, string = '_sage_field_novedadesweb')
	_sage_field_idarticulo = fields.Char(required = False, string = '_sage_field_idarticulo')
	_sage_field_publicargcrm = fields.Char(required = False, string = '_sage_field_publicargcrm')
	_sage_field_mesesgarantiaventa = fields.Char(required = False, string = '_sage_field_mesesgarantiaventa')
	_sage_field_mesesgarantiacompra = fields.Char(required = False, string = '_sage_field_mesesgarantiacompra')
	_sage_field_mesesgarantiareparacion = fields.Char(required = False, string = '_sage_field_mesesgarantiareparacion')
	_sage_field_fechamodificacion = fields.Char(required = False, string = '_sage_field_fechamodificacion')
	_sage_field_fecharecepcionsumex = fields.Char(required = False, string = '_sage_field_fecharecepcionsumex')
	_sage_field_factors = fields.Char(required = False, string = '_sage_field_factors')
	_sage_field_estaencatalogo = fields.Char(required = False, string = '_sage_field_estaencatalogo')
	_sage_field_codigoalternativo3 = fields.Char(required = False, string = '_sage_field_codigoalternativo3')
	_sage_field_largo_ = fields.Char(required = False, string = '_sage_field_largo_')
	_sage_field_ancho_ = fields.Char(required = False, string = '_sage_field_ancho_')
	_sage_field_alto_ = fields.Char(required = False, string = '_sage_field_alto_')
	_sage_field_fabricadoen = fields.Char(required = False, string = '_sage_field_fabricadoen')
	_sage_field_s_codigofiscalproducto = fields.Char(required = False, string = '_sage_field_s_codigofiscalproducto')
	_sage_field_moq = fields.Char(required = False, string = '_sage_field_moq')
	_sage_field_udcajaouter = fields.Char(required = False, string = '_sage_field_udcajaouter')
	_sage_field_udcajainner = fields.Char(required = False, string = '_sage_field_udcajainner')
	_sage_field_largoouter = fields.Char(required = False, string = '_sage_field_largoouter')
	_sage_field_largoinner = fields.Char(required = False, string = '_sage_field_largoinner')
	_sage_field_anchoouter = fields.Char(required = False, string = '_sage_field_anchoouter')
	_sage_field_anchoinner = fields.Char(required = False, string = '_sage_field_anchoinner')
	_sage_field_altoouter = fields.Char(required = False, string = '_sage_field_altoouter')
	_sage_field_altoinner = fields.Char(required = False, string = '_sage_field_altoinner')
	_sage_field_gwouter = fields.Char(required = False, string = '_sage_field_gwouter')
	_sage_field_gwinner = fields.Char(required = False, string = '_sage_field_gwinner')
	_sage_field_nwouter = fields.Char(required = False, string = '_sage_field_nwouter')
	_sage_field_nwinner = fields.Char(required = False, string = '_sage_field_nwinner')
	_sage_field_volumenouter = fields.Char(required = False, string = '_sage_field_volumenouter')
	_sage_field_volumeninner = fields.Char(required = False, string = '_sage_field_volumeninner')
	_sage_field_codigotembalaje = fields.Char(required = False, string = '_sage_field_codigotembalaje')
	_sage_field_estaentarifa = fields.Char(required = False, string = '_sage_field_estaentarifa')
	_sage_field_articuloequivalente = fields.Char(required = False, string = '_sage_field_articuloequivalente')
	_sage_field_fechaprevistasumex = fields.Char(required = False, string = '_sage_field_fechaprevistasumex')

	@api.model
	def create(self, vals_list):

		if 'from_import_csv' not in self._context:
			return super(sumex_apps_sage_inherits_sage_product_inherit, self).create(vals_list)
		vals_list['_created_from_sumex_apps_imports_csv_of_sage'] = True
		rows = super(sumex_apps_sage_inherits_sage_product_inherit, self).create(vals_list)
		return rows

	def write(self, vals_list):

		if 'from_import_csv' not in self._context:
			return super(sumex_apps_sage_inherits_sage_product_inherit, self).write(vals_list)
		vals_list['_created_from_sumex_apps_imports_csv_of_sage'] = True
		rows = super(sumex_apps_sage_inherits_sage_product_inherit, self).write(vals_list)
		return rows
